# Generated by Django 3.1.7 on 2021-03-01 16:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('encoding', models.CharField(default='UTF-8', max_length=20, verbose_name='Encoding')),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Created')),
                ('updated', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Updated')),
                ('public', models.BooleanField(default=True, verbose_name='Public')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('encoding', models.CharField(default='UTF-8', max_length=20, verbose_name='Encoding')),
                ('handler', models.CharField(max_length=128, verbose_name='Handler')),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Created')),
                ('updated', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Updated')),
                ('public', models.BooleanField(default=False, verbose_name='Public')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='filemanager.project')),
            ],
            options={
                'unique_together': {('name', 'owner', 'project')},
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('external_name', models.CharField(max_length=254, verbose_name='External Name')),
                ('text', models.TextField(verbose_name='text')),
                ('encoding', models.CharField(default='UTF-8', max_length=20, verbose_name='Encoding')),
                ('handler', models.CharField(max_length=128, verbose_name='Handler')),
                ('length', models.IntegerField(default=0, verbose_name='Length (chars)')),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Created')),
                ('updated', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Updated')),
                ('public', models.BooleanField(default=False, verbose_name='Public')),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='filemanager.collection')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_by', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='filemanager.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'owner', 'collection', 'project')},
            },
        ),
    ]
