# Generated by Django 3.1.6 on 2021-02-14 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Project Name')),
                ('created', models.DateTimeField(verbose_name='Date Created')),
                ('updated', models.DateTimeField(verbose_name='Date Updated')),
                ('public', models.BooleanField(default=True, verbose_name='Public')),
                ('encoding', models.CharField(default='UTF-8', max_length=20, verbose_name='Encoding')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
