# Generated by Django 3.1.6 on 2021-02-14 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
