# Generated by Django 3.1.6 on 2021-02-14 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filemanager', '0002_auto_20210214_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('encoding', models.CharField(default='UTF-8', max_length=20, verbose_name='Encoding')),
                ('handler', models.CharField(max_length=128, verbose_name='Handler')),
                ('created', models.DateTimeField(verbose_name='Date Created')),
                ('updated', models.DateTimeField(verbose_name='Date Updated')),
                ('public', models.BooleanField(default=True, verbose_name='Public')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('external_name', models.CharField(max_length=124, verbose_name='Name')),
                ('text', models.TextField(verbose_name='text')),
                ('encoding', models.CharField(default='UTF-8', max_length=20, verbose_name='Encoding')),
                ('handler', models.CharField(max_length=128, verbose_name='Handler')),
                ('created', models.DateTimeField(verbose_name='Date Created')),
                ('updated', models.DateTimeField(verbose_name='Date Updated')),
                ('public', models.BooleanField(default=True, verbose_name='Public')),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='filemanager.collection')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='filemanager.project'),
        ),
    ]
