# Generated by Django 3.1.6 on 2021-02-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0003_auto_20210214_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='length',
            field=models.IntegerField(default=0, verbose_name='Length (chars)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='external_name',
            field=models.CharField(max_length=254, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
    ]
