# Generated by Django 3.0.5 on 2021-05-13 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clarin_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='permission',
            new_name='permissions',
        ),
    ]
