# Generated by Django 3.1.6 on 2021-05-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clarin_backend', '0002_auto_20210513_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opendocuments',
            name='id',
        ),
        migrations.AlterField(
            model_name='opendocuments',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(default=None, max_length=255, null=True, unique=True, verbose_name='first_name'),
        ),
    ]
